name: ci
on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          persist-credentials: false

      - name: Setup environment
        uses: cachix/install-nix-action@v16

      - name: Install dependencies
        run: nix-shell --run "make install-dev"

      - name: Run static analysis checks
        run: nix-shell --run "make check"

      - name: Run tests
        run: nix-shell --run "make test"
